export type RootStackParamList = {
    Splash:undefined;
    Login:undefined;
    ChangePassword:undefined;
    Registeredfarmer:undefined;
    Ufarmercropdetails:undefined;
    Dashboard:undefined;
    QRScanner:undefined;
    FormScreen: { scannedData: any };
    EngProfile:undefined;
    UnregisteredFarmerDetails:{ cropCount: 1, userId:number };
    UnregisteredCropDetails: { cropCount: number, userId:number };
    SinChangePassword:undefined;
    SinLogin:undefined;
    Lanuage:undefined;
    SinDashboard:undefined;
    SinUfarmercropdetails:undefined;
    SinUnregisteredCropDetails: { cropCount: number };
    SinUnregisteredFarmerDetails:undefined;
    SinRegisteredfarmer:undefined;
    TamChangePassword:undefined;
    TamLogin:undefined;
    TamDashboard:undefined;
    TamRegisteredfarmer:undefined;
    TamUfarmercropdetails:undefined;
    TamUnregisteredFarmerDetails:undefined;
    TamUnregisteredCropDetails:{ cropCount: number,userId:any };
    SinProfile:undefined;
    TamProfile:undefined;
    SearchFarmer:undefined;

};